branch-defaults:
  master:
    environment: armybuilder-dev
    group_suffix: null
  pdf_parsing:
    environment: armybuilder-dev
environment-defaults:
  armybuilder-dev:
    branch: null
    repository: null
global:
  application_name: armybuilder
  branch: null
  default_ec2_keyname: armybuilder-aws-db
  default_platform: Docker 18.09.9-ce
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
